### ISSUE TITLE
Can ruODK be used to edit submissions in a form?

### ISSUE THREAD

**Issue by ocelhay** [ropensci/ruODK#113]
This is more of a questions than an issue, sorry if it's not the right venue.

I have been looking at https://odkcentral.docs.apiary.io but it's unclear to me if the API allow it. Do you have know if the API/ruODK can be used to edit submissions in a form?

**Comment by florianm** [comment]
Good question, and certainly a useful feature.

It's on the roadmap for ODK Central 1.2 but currently not yet implemented in the Central API, so ruODK doesn't support this feature yet.

My goal is to implement ruODK functions for each API endpoint as they are added, modified, and removed, so this feature will eventually be implemented in ruODK.

**Comment by florianm** [comment]
I'm closing this issue seeing that new ODK features, such as editing submissions, are on the ruODK roadmap. Thanks again for suggesting it and giving ruODK a go!

**Comment by florianm** [comment]
Update: 
* Implementation roadmap in ruODK https://github.com/ropensci/ruODK/issues/123
* ODK Central 1.2 release (pinned issue) https://github.com/getodk/central/issues/198

**Comment by adithirgis** [comment]
Hello, 

I wanted to know if there are worked out examples using `ruODK` examples for editing the forms / submissions. 
Thanks

**Comment by florianm** [comment]
In the upcoming release supporting entities the updating functions (as all other functions) will have working examples. A vignette is on the horizon, although once all endpoints are supported, the workflows from the official ODK docs should be straightforward to implement.

I'm abroad atm and will resume work on the release in late October.
