### ISSUE TITLE
publishedAt should be used to identify form drafts

### ISSUE THREAD

**Issue by lognaturel** [ropensci/ruODK#119]
https://github.com/ropensci/ruODK/issues/86 added filtering out unpublished forms from form lists. Looking at the tests [here](https://github.com/ropensci/ruODK/blob/1f72c5a5ce2a547345792cc8412de1395fe13e33/tests/testthat/test-form_list.R) this uses `version` and `hash` to identify unpublished forms. However, those are only incidentally `null` in Central versions < 1.2 and will be populated in Central v1.2+. 

From [the docs](https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/forms/list-all-forms): 
* `version`: `The version of this form as given in its XForms XML definition.`
* `hash`: `An MD5 sum automatically computed based on the XForms XML definition.`

The intended way to identify unpublished form is to match on `publishedAt` of `null` (e.g. [in Briefcase](https://github.com/getodk/briefcase/pull/885/files#diff-5a8300e35e48cb417082f6f44e1d6e7d57c08ba7f5008e195f0f69a9fd6ba6a8)). We now see this lacks documentation and will make sure that is updated. `publishedAt` exists for all Central versions that include drafts. To support earlier versions (though we don't recommend it), you could first check for the existence of `publishedAt`. If it doesn't exist, the form can be included because there can be no drafts to filter out.

**Comment by florianm** [comment]
![IMG_20210427_175938.jpg](https://user-images.githubusercontent.com/762815/116223719-66f74400-a782-11eb-9aaa-6a3b2e20b147.jpg)
Sophie had a general review comment on ODK

**Comment by florianm** [comment]
Fixed by adding `published_at` to `form_list` and `form_detail`, and clarifying in examples how to find form drafts. Thanks for the detailed bug report, @lognaturel!

**Comment by lognaturel** [comment]
Yaaaay, Sophie! Can't wait for your first pull request! 😊
