### ISSUE TITLE
Table describing which ruODK version corresponds to which ODK Central

### ISSUE THREAD

**Issue by collinschwantes** [ropensci/ruODK#143]
## Feature

I have run into issues with certain functions assuming a certain version of ODK Central - specifically related to the `review state` attribute because I am not running (and am not ready to up date to) the most recent version of ODK central. 

It would be nice to know which version of the ruODK package should be used with which version of ODK Central. Along those same lines, it may be useful to generate releases on github for each version. 

ruODK Package | ODK Central | commit hash
----------------| --------------| ----------
1.0.0| 1.1.1| sdf823
...|...|...
X.1.0 | X.2.2| a39m4u

If using `renv` install a package version like this:

```
renv::install("ropensci/ruODK@some_commit_hash")
```

**Comment by florianm** [comment]
Hi @collinschwantes! Thanks for the suggestion!

First, I'm about to push a fix to #145 (`reviewState`).

Second, ruODK should ideally work with every ODK Central version - you can set the `ODKC_VERSION` variable to toggle ruODK's behaviour for breaking changes to the Central API. Non-breaking API changes like #145 should be handled gracefully by ruODK - I'm slowly working my way through all the little API additions. Bug reports such as this one are always appreciated, as they help me chase them down!

I'm closing this issue as #145 is fixed, and the latest ruODK version should always work best.
