### ISSUE TITLE
Account request for ODK Central test instance for ruODK package tests

### ISSUE THREAD

**Issue by agusk81** [ropensci/ruODK#147]
I would like to run the tests.
Please provide access to the ODK Central test instance for ruODK <https://odkc.dbca.wa.gov.au/>.

[ ] I have sent an email to the `ruODK` package maintainer requesting access.
[ ] I will not use the server to run production campaigns.

**Comment by florianm** [comment]
Hi @agusk81, with apologies for the lag in reponse: ruODK is currently migrating to a new test server, and unfortunately we are not in a position to allow for external access to the test server.

The test suite will skip tests that require a test server and pull requests will run against the ruODK test server.

Closing this issue but appreciate any issues or pull requests!
