### ISSUE TITLE
Support encryption

### ISSUE THREAD

**Issue by florianm** [ropensci/ruODK#30]
## Feature
Support data retrieval from encrypted projects.
Docs: https://docs.getodk.org/central-encryption/

### Caveats
* Encrypted data is not available via OData, only via CSV/ZIP export

### In scope
* Project managed encryption (see [docs](https://docs.getodk.org/central-encryption/))
* https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/submissions/exporting-form-submissions-to-csv-via-post
  * ruODK::submission_export - change from GET to POST and add optional param for encryption key.
* Double check - does the API endpoint called by ruODK::submission_get [docs](https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/submissions/getting-submission-details) work in encrypted projects?
* Double check - what happens with ruODK::odata_submission_get() in encrypted projects? Should ruODK emit a warning that only metadata are returned?

### Nice to have
* https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/submissions/listing-encryption-keys
* Which other functions would provide value to users of encrypted projects? Paging @dmenne @michaeledwardmarks @Thaliehln
* Vignette "Honey I've encrypted the kids" to demonstrate workflow with encrypted projects. e.g.:
  * Enable encryption through GUI: link to ODK docs https://docs.getodk.org/central-encryption/#using-project-managed-encryption
  * Collect some data (we'll use the test form)
  * Export submissions via all new ruODK::submission_export() with encryption keys and POST
  * Visualise the decrypted data
  * Mention out of scope encryption features of ODK Central and solicit user feedback on what's missing

### Out of scope
* Enabling project managed encryption through ruODK 
  * https://odkcentral.docs.apiary.io/#reference/project-management/projects/enabling-project-managed-encryption 
  * best done through ODK Central's GUI, since this is a one-off per project it would spam the test server with new/encrypted/deleted projects.
* https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/submissions/exporting-form-submissions-to-csv via GET

### MVP
- [x] https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/submissions/exporting-form-submissions-to-csv-via-post with optional encryption passphrase
- [x] One new encrypted test project on test server: https://odkc.dbca.wa.gov.au/#/projects/3/forms/Locations with Passphrase **ThePassphrase**

**Comment by florianm** [comment]
Since forms cannot be un-encrypted, writing tests for form encryption will lead to a proliferation of forms or will require programmatic creation, permission handling, publishing, encryption, (testing goes here), and deletion of forms.

We could add one encrypted test form and support download / decryption of that form.

**Comment by florianm** [comment]
#96 now provides an encrypted test project with one form with (so far) one submission. The contrib guidelines are updated with the required settings. @Thaliehln we should be good to go!

**Comment by florianm** [comment]
Thanks to @Thaliehln for #110 - closing this issue, and shifting remaining ideas to #111 and #112

**Comment by Thaliehln** [comment]
Hi @florianm, I have just noticed that the submission export request crashes the ODK Central server if the passphrase given in argument is incorrect, which is less than ideal if the server is shared between different projects. I will have a look at the API doc to try to see if there is a way to avoid this. I think it may be due to the fact the requests is retried until it succeeds (which is not possible with an incorrect passphrase), in which case it may be possible to check the request response is different when there is an incorrect passphrase (although I only see 200, 400 and 403.1 in the doc, but I may be missing something).
I think there should be a warning in the meantime, so that users know they may need to restart their ODK Central services in case they used an incorrect passphrase.

**Comment by florianm** [comment]
Thanks for the heads-up! I haven't use too many encrypted forms beyond my test cases so I didn't come across this behaviour yet.
Sounds like a bug in Central. 
Does the server crash on the first try or on repeated retries? We could set retries=1 in the latter case. Our default is 3, so it shoudl stop after three requests anyways. Error handling with informative messages would certainly be a great idea too.

**Comment by Thaliehln** [comment]
Thanks! I had also missed that during my initial (although much less systematic than your unitary) tests, but I have now eventually encrypted the dummy database I am intensively testing.
From a few more tests, and as posted on the ODK forum, the server gets unresponsive on repeated retries (with my server / configuration after 3-4 unsuccessful attempts times retries). The ODK Central returned code should be `400.12` - (Could not perform decryption. Double check your passphrase and your data and try again). I will try to reproduce the bug with the 0.10.1 patch setting retries=1, although my intuition would be that this may decrease the likelihood of encountering the issue when configuring the export, but may also increase the likelihood of failing retrieving data if the connection is a bit unpredictable - in which case this may not be an ideal trade-off for ruODK users, but let's see already what happens.

**Comment by florianm** [comment]
@Thaliehln the latest patch terminates RETRY immediately on HTTP status 500, which is returned by ODK Central on wrong passphrases. I've also improved the troubleshooting tips with a mention to check the passphrase.

**Comment by florianm** [comment]
Even one request with a failing passphrase sent from 11 GHA and one Appveyor = 12 test environments managed to crash my ODK Central server.
