### ISSUE TITLE
How to get labels and hints

### ISSUE THREAD

**Issue by dmenne** [ropensci/ruODK#77]
A snippet to get labels and hints into the form_schema. Must be improved when translations are present. "guidance" field may need a second look, and an XPATH expert could simplify the paths.

Feel free to use or not

```
library(ruODK)
library(xml2)
library(dplyr)
library(stringr)
library(tidyr)

ru_setup(
  svc = "https:xxxxx",
  un = "yy",
  pw = "xx",
  tz = Sys.timezone()
) 


f_xml = as_xml_document(form_xml())
ff_xml = tibble(
  # Remove trailing /data
  path= str_sub(xml_text(xml_find_all(f_xml, "//translation/text/@id")),6),
  label = xml_text(xml_find_all(f_xml, "//translation/text"))
)%>% 
  separate(path, sep=":", into=c("path", "type")) %>% 
  pivot_wider(names_from=type, values_from=label)

fs_extended = form_schema(flatten = FALSE) %>% 
  left_join(ff_xml, by="path")

```

Here an example from the xml-file
```
        <translation default="true()" lang="Deutsch (de)">
          <text id="/data/pat_gruppe:label">
            <value>Patient</value>
          </text>
          <text id="/data/pat_gruppe/pat_no_barcode:label">
            <value>Patienten-Barcode</value>
          </text>
```

**Comment by florianm** [comment]
Thanks Dieter! I'll add this to form_schema_parse (used up to odkc v7) and submit a feature request for the new form_schema (direct JSON from odkc) to include these.

**Comment by dmenne** [comment]
Better not yet. I will try more forms and update you. This was a first try.

**Comment by matthew-white** [comment]
Part of me thinks that it could be useful to add something like this to the Central API: there may be enough use cases where a user needs these labels that the best approach would be for Central to provide that information. Feel free to create a topic in the Features category of the ODK forum if something along those lines would be helpful!

**Comment by florianm** [comment]
@matthew-white it would be awesome to have labels and hints included in https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/'-individual-form/getting-form-schema-fields, e.g. as nested list

```
  {
    "name": "age",
    "path": "/age",
    "type": "int",
    "label": {"en": "Age", "de": "Alter"},
    "hint": {"en": "...", "de": "..."}
  },
```

**Comment by mtyszler** [comment]
I submitted an issue at Central (https://github.com/getodk/central/issues/172)

**Comment by mtyszler** [comment]
@dmenne 

This is a good solution: 

> ru_setup(
>   svc = "https:xxxxx",
>   un = "yy",
>   pw = "xx",
>   tz = Sys.timezone()
> ) 
> 
> 
> f_xml = as_xml_document(form_xml())
> ff_xml = tibble(
>   path= str_sub(xml_text(xml_find_all(f_xml, "//translation/text/@id")),6),
>   label = xml_text(xml_find_all(f_xml, "//translation/text"))
> )%>% 
>   separate(path, sep=":", into=c("path", "type")) %>% 
>   pivot_wider(names_from=type, values_from=label)
> 
> fs_extended = form_schema(flatten = FALSE) %>% 
>   left_join(ff_xml, by="path")
> ```

This is a good solution, but please be aware that this works only when there are multiple translations. If there is a single document, labels are stored in a different way (there's no translation element in the XML tree).

I'll submit a suggestion soon.

**Comment by florianm** [comment]
Nice work! This would warrant a new test form. Unit tests could run against that form, and also against the current forms without translations.

**Comment by dmenne** [comment]
Great! I had already noted that the function failed sometimes, but did not have the time to test out why. You saved my days!
