### ISSUE TITLE
form_list returns error when there is a testing form

### ISSUE THREAD

**Issue by dmenne** [ropensci/ruODK#86]
- I have a project with a few forms, all published
- Calling form_list() works fine
- Add a new form for testing, no submissions

form_list errors with "Result 2 must be a single string, not NULL of length 0"

**Comment by florianm** [comment]
Cheers Dieter, I'll have a look! Warrants a new test case methinks.

**Comment by dmenne** [comment]
Currently I have difficulties reproducing it. Will do further checks.

**Comment by dmenne** [comment]
Issue is still reproducable. Any progress?

**Comment by dmenne** [comment]
See my pull request. session and hash are NULL for drafts

**Comment by florianm** [comment]
Thanks for the PR, merged!
I've added an empty form without submissions ("Locations no submissions please") to the ruODK test project.
Without the PR, the tests for form_list fail. With the added ".default = NA" as per PR, the tests pass.
