### ISSUE TITLE
RETRY: Global allow for fail after one try

### ISSUE THREAD

**Issue by dmenne** [ropensci/ruODK#94]
ruODK uses RETRY for most httr requests. This is a good idea for real life internet operations, but when running tests it slow down everything considerable.

It would be nice if parameter `times` in RETRY could be set by some global action to 1.

**Comment by florianm** [comment]
That makes absolute sense, thanks for the suggestion!
I will add `times = ruODK::get_default_retries()` to all `httr::GET` calls, which in turn should read an enviornment variable like `RU_RETRIES` with a default of 3 (the current value).

**Comment by dmenne** [comment]
Perfect!
