### ISSUE TITLE
Account request for ODK Central instances used by ruODK

### ISSUE THREAD

**Issue by mtyszler** [ropensci/ruODK#97]
I want to run the tests and build the vignettes. 
Please provide access to the ODK Central test instance for ruODK <https://ruodk.getodk.cloud/>.

[ ] I have sent an email to the `ruODK` package maintainer requesting access.
[X ] I will not use the server to run production campaigns.

**Comment by mtyszler** [comment]
Hi, 

I want to test to provide a PR based on issue #77

**Comment by florianm** [comment]
Hi @mtyszler! Thanks for your contribution!
The new test server is not up yet, so I'll send you an invite to the ODK Central Sandbox, where the unit tests currently live to the email on your GH profile.

**Comment by mtyszler** [comment]
Tks @florianm . Once I get the invite I'll close this if succeed to access the test form

**Comment by mtyszler** [comment]
Tks @florianm. Account is all set!
