### ISSUE TITLE
Vignette broken

### ISSUE THREAD

**Issue by jeroen** [ropensci/ruODK#99]
See https://dev.ropensci.org/job/ruODK/lastBuild/console

**Comment by florianm** [comment]
Thanks for the bug report! That's fallout from the recent migration of the test server which brought new test data submissions. Will address shortly.

**Comment by florianm** [comment]
Seems fixed apart from the pesky `check_title` warning (where do I disable that?), thanks again for the report, and now I have Nena's 99 Luftballons stuck in my head.
